FROM alpine:3.6 as alpine

RUN apk add -U --no-cache ca-certificates tzdata

ARG TZ=Asia/Shanghai
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV ENVIRONMENT TEST

ADD dist/recative-backend /app/

EXPOSE 12211

WORKDIR /app

RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

ENTRYPOINT ["/app/recative-backend"]
