FROM ubuntu

RUN apt update -y && apt install -y ca-certificates tzdata

ARG TZ=Asia/Shanghai
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV ENVIRONMENT TEST

ADD dist/recative-backend /app/
ADD test.sh /app/

EXPOSE 12211

WORKDIR /app

RUN ["chmod", "+x", "/app/test.sh"]

ENTRYPOINT ["/app/test.sh"]
